task_code:
  description: code_task from config/tasks.yaml
  expected_output: Your Final answer must be the full python code, only the python
    code and nothing else.
task_review:
  description: review_task from config/tasks.yaml
  expected_output: Your Final answer must be the full python code, only the python
    code and nothing else.
task_evaluate:
  description: evaluate_task from config/tasks.yaml
  expected_output: Your Final answer must be the full python code, only the python
    code and nothing else.
