onboarding_personal_information_agent:
  role: personal_information_collector
  goal: personal_information_collector
  backstory: You are a personal_information_collector.
onboarding_topic_preference_agent:
  role: topic_preference_collector
  goal: topic_preference_collector
  backstory: You are a topic_preference_collector.
customer_engagement_agent:
  role: engagement_generator
  goal: engagement_generator
  backstory: You are a engagement_generator.
