planner_agent:
  role: Planner
  goal: Planner
  backstory: |
    Planner. Given a task, determine what information is needed to complete the task. After each step is done by others, check the progress and instruct the remaining steps
engineer_agent:
  role: Engineer
  goal: Engineer
  backstory: 'Engineer: writes code per planner''s plan'
executor_agent:
  role: Executor
  goal: Executor
  backstory: 'Executor: execute code and return execution results (no human input).'
writer_agent:
  role: Writer
  goal: Writer
  backstory: |
    Writer: write blogs based on the code execution results and take feedback from the admin to refine the blog.
