"""
Auto-generated CrewAI Crew: UnnamedProject

Source  : AgentO Knowledge Graph → SPARQL → Pydantic → Jinja2
Pipeline: 3-Layer Conversion Pipeline
Capabilities:
  - create draft document: Tool capability: prepare a text document with title and description according to a schema.
  - document generation: Agent capability: generate textual document content based on user messages and prompts.
  - tool binding: Agent capability: bind schema-defined tools to model so model can produce tool calls.
  - streaming output: Agent can process streaming outputs (chunks) from the language model and concatenate them into messages.
Resources:
  - : Represents the sequence 'state.messages' passed into each node: initial messages from the user and system, including earlier AI messages and tool call fragments. Used as input to model invocations and tool binding.
  - : The last AI message in conversation state.messages, used by the suggestions step to examine .tool_calls and to create tool-completion messages.
  - draft candidate: Resource produced by the prepare node's draft_text_document tool call. Contains fields 'title' and 'description' as specified by the tool schema. In implementation this is created by reading the tool call args from streamed message chunks.
  - final document: Full document content generated by the writer node (system instruction requests only content). In implementation this is assembled from contentStream chunks or returned via non-stream invocation depending on tags.
  - : Message produced by the suggestions task consisting of the model's finish output after tool-call finalization (the 'Finished' tool messages are added prior to invocation).
"""

from crewai import Agent, Crew, Process, Task
from crewai.project import CrewBase, agent, crew, task
from crewai.tools import tool


# ===========================================================
# Tool Instances
# ===========================================================
# TODO: draft_text_document_tool — unknown tool class "drafttextdocument"
#   Implement as a custom BaseTool or replace with a crewai_tools equivalent.
@tool("drafttextdocument")
def draft_text_document_tool(*args, **kwargs) -> str:
    """Prepare a text document for the user with a short title and short description for browsing purposes."""
    return "draft_text_document_tool result"




@CrewBase
class UnnamedProject:
    """UnnamedProject crew"""

    agents_config = 'config/agents.yaml'
    tasks_config = 'config/tasks.yaml'

    # ── Agents ──────────────────────────────────────────

    @agent
    def writer_annotation_agent_uuid_1(self) -> Agent:
        return Agent(
            config=self.agents_config['writer_annotation_agent_uuid_1'],
            tools=[draft_text_document_tool],
        )

    # ── Tasks ───────────────────────────────────────────

    @task
    def prepare_task(self) -> Task:
        return Task(
            config=self.tasks_config['prepare_task'],
            agent=self.writer_annotation_agent_uuid_1(),
        )

    @task
    def write_task(self) -> Task:
        return Task(
            config=self.tasks_config['write_task'],
            agent=self.writer_annotation_agent_uuid_1(),
            context=[self.prepare_task()],
        )

    @task
    def suggestions_task(self) -> Task:
        return Task(
            config=self.tasks_config['suggestions_task'],
            agent=self.writer_annotation_agent_uuid_1(),
        )

    # ── Crew ────────────────────────────────────────────

    @crew
    def crew(self) -> Crew:
        """Creates the UnnamedProject"""
        return Crew(
            agents=self.agents,
            tasks=self.tasks,
            process=Process.sequential,
            verbose=True,
        )
