"""
Auto-generated CrewAI Crew: UnnamedProject

Source  : AgentO Knowledge Graph → SPARQL → Pydantic → Jinja2
Pipeline: 3-Layer Conversion Pipeline
Environments:
  -  (local-development): Configuration indicates use of localhost postgres and local services (from source code constants).
Capabilities:
  - use memory: Capability to store and recall conversation history via the SharedMemoryStore.
  - suggest recipes: Capability to propose recipes and high-level cooking steps given ingredient lists.
Resources:
  - : Logical resource id used as the memory resource key for conversation threading (from source code: const resource = 'SOME_USER_ID').
  - : Example thread id used in chat.ts for long running conversation testing.
  - : Text output from ChefAgent in response to Prompt_Index_WhatCanIMake. Contains high-level steps.
  - : Text output from ChefAgent in response to Prompt_Index_FriendsHouse.
  - : Text output from ChefAgent summarizing prior recipe suggestions (requested via Prompt_Index_RecallPrevious).
  - : Text produced by MemoryAgent after system start prompt (Prompt_Chat_SystemStart).
  - : General chat response generated by MemoryAgent for user-provided messages.
"""

from crewai import Agent, Crew, Process, Task
from crewai.project import CrewBase, agent, crew, task




@CrewBase
class UnnamedProject:
    """UnnamedProject crew"""

    agents_config = 'config/agents.yaml'
    tasks_config = 'config/tasks.yaml'

    # ── Agents ──────────────────────────────────────────

    @agent
    def chef_agent(self) -> Agent:
        return Agent(
            config=self.agents_config['chef_agent'],
        )

    @agent
    def memory_agent(self) -> Agent:
        return Agent(
            config=self.agents_config['memory_agent'],
        )

    # ── Tasks ───────────────────────────────────────────

    @task
    def task_recipe_suggest_initial_query(self) -> Task:
        return Task(
            config=self.tasks_config['task_recipe_suggest_initial_query'],
            agent=self.chef_agent(),
        )

    @task
    def task_chat_start_conversation(self) -> Task:
        return Task(
            config=self.tasks_config['task_chat_start_conversation'],
            agent=self.memory_agent(),
        )

    @task
    def task_recipe_suggest_friends_house_query(self) -> Task:
        return Task(
            config=self.tasks_config['task_recipe_suggest_friends_house_query'],
            agent=self.chef_agent(),
        )

    @task
    def task_chat_interactive_message(self) -> Task:
        return Task(
            config=self.tasks_config['task_chat_interactive_message'],
            agent=self.memory_agent(),
        )

    @task
    def task_recipe_suggest_recall_previous(self) -> Task:
        return Task(
            config=self.tasks_config['task_recipe_suggest_recall_previous'],
            agent=self.chef_agent(),
        )

    # ── Crew ────────────────────────────────────────────

    @crew
    def crew(self) -> Crew:
        """Creates the UnnamedProject"""
        return Crew(
            agents=self.agents,
            tasks=self.tasks,
            process=Process.sequential,
            verbose=True,
        )
