cv_reader:
  role: CV Reader
  goal: CV Reader
  backstory: |
    Agent-level prompt to orient behavior. Use FileReadTool to access CV file. Produce a structured CV summary.
  allow_delegation: false
  verbose: false
matcher:
  role: Matcher
  goal: Matcher
  backstory: |
    Agent-level prompt to orient behavior. Use CSVSearchTool and FileReadTool to access jobs CSV and CV summary.
  allow_delegation: false
  verbose: false
