"""
Auto-generated CrewAI Crew: UnnamedProject

Source  : AgentO Knowledge Graph → SPARQL → Pydantic → Jinja2
Pipeline: 3-Layer Conversion Pipeline
Resources:
  - : Trigger input resource representing the resume text provided to the workflow. Example value used in code run: 'Simulated resume content...'
  - : Structured output produced by gatherCandidateInfo task.
Fields:
- candidateName: string
- isTechnical: boolean
- specialty: string
- resumeText: string
This instance represents the structured candidate information produced by the task.
  - : A short question generated by askAboutSpecialty task (output schema: { question: string }).
  - : A short question generated by askAboutRole task (output schema: { question: string }).
"""

from crewai import Agent, Crew, Process, Task
from crewai.project import CrewBase, agent, crew, task




@CrewBase
class UnnamedProject:
    """UnnamedProject crew"""

    agents_config = 'config/agents.yaml'
    tasks_config = 'config/tasks.yaml'

    # ── Agents ──────────────────────────────────────────

    @agent
    def recruiter_agent(self) -> Agent:
        return Agent(
            config=self.agents_config['recruiter_agent'],
        )

    # ── Tasks ───────────────────────────────────────────

    @task
    def gather_candidate_info(self) -> Task:
        return Task(
            config=self.tasks_config['gather_candidate_info'],
            agent=self.recruiter_agent(),
        )

    @task
    def ask_about_specialty(self) -> Task:
        return Task(
            config=self.tasks_config['ask_about_specialty'],
            agent=self.recruiter_agent(),
            context=[self.gather_candidate_info()],
        )

    @task
    def ask_about_role(self) -> Task:
        return Task(
            config=self.tasks_config['ask_about_role'],
            agent=self.recruiter_agent(),
            context=[self.gather_candidate_info()],
        )

    # ── Crew ────────────────────────────────────────────

    @crew
    def crew(self) -> Crew:
        """Creates the UnnamedProject"""
        return Crew(
            agents=self.agents,
            tasks=self.tasks,
            process=Process.sequential,
            verbose=True,
        )
