"""
Auto-generated CrewAI Crew: UnnamedProject

Source  : AgentO Knowledge Graph → SPARQL → Pydantic → Jinja2
Pipeline: 3-Layer Conversion Pipeline
Goals:
  - : Goal: exercise agent-to-agent communication via A2A protocol, fetch research, and create an engaging blog introduction from the research.
Objectives:
  - : Objective assigned to the team: gather research on agent networks and produce engaging content. Tasks ResearchTask and ContentTask contribute to this objective.
Resources:
  - : Dynamic response from MyAgent to the initial query. Captured at runtime by the example. Placeholder: ${initialQueryResponse}. The exact content is produced by the connected language model and is not present in the static source.
  - : Dynamic textual research produced by MyAgent in response to the ResearchTask. At runtime the code stores the result in a variable 'researchResult' and passes it (partially printed) to the second agent. Placeholder for the actual research output: ${researchResult}.
  - : Dynamic textual content generated by the Content Creator Agent from the ResearchResult input. Placeholder: ${contentResult}. Actual generated content appears at runtime.
"""

from crewai import Agent, Crew, Process, Task
from crewai.project import CrewBase, agent, crew, task




@CrewBase
class UnnamedProject:
    """UnnamedProject crew"""

    agents_config = 'config/agents.yaml'
    tasks_config = 'config/tasks.yaml'

    # ── Agents ──────────────────────────────────────────

    @agent
    def my_agent(self) -> Agent:
        return Agent(
            config=self.agents_config['my_agent'],
        )

    @agent
    def content_creator_agent(self) -> Agent:
        return Agent(
            config=self.agents_config['content_creator_agent'],
        )

    # ── Tasks ───────────────────────────────────────────

    @task
    def research_task(self) -> Task:
        return Task(
            config=self.tasks_config['research_task'],
            agent=self.my_agent(),
        )

    @task
    def content_task(self) -> Task:
        return Task(
            config=self.tasks_config['content_task'],
            agent=self.content_creator_agent(),
            context=[self.research_task()],
        )

    @task
    def initial_query_task(self) -> Task:
        return Task(
            config=self.tasks_config['initial_query_task'],
            agent=self.my_agent(),
        )

    # ── Crew ────────────────────────────────────────────

    @crew
    def crew(self) -> Crew:
        """Creates the UnnamedProject"""
        return Crew(
            agents=self.agents,
            tasks=self.tasks,
            process=Process.sequential,
            verbose=True,
        )
